# loki-minimal.yaml
auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /var/loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  filesystem:
    directory: /var/loki/tsdb

ruler:
  alertmanager_url: http://my_alertmanager:9093
  rule_path: /var/loki/rules   # Ruler가 쓰기 가능한 scratch 경로 (tenant 하위가 생성됨)
  storage:
    type: local
    local:
      directory: /etc/loki/rulestorage  # 실제 규칙 파일이 위치하는 경로 (tenant 하위 필요)
